services:
  backend:
    build: ./backend
    container_name: store-backend
    ports:
      -  "5000-5000"

  frontend:
    build: ./frontend
    container_name: store-frontend
    ports:
      -  "8080:80"
    depends_on:
      -  backend
